### ISSUE TITLE
Thank you, GitHub.

### ISSUE THREAD

**Issue by chiefGui** [thank-you-github/thank-you-github#1080]
Hello there.

I don't want to create any noise around here, but I'd like to extend the letter a little and say to GitHub that they sparked on me something that went beyond code.

I started programming not long ago. I'm not into the early generations of programmers that had to learn by reading books. My first time playing with code was in 2005 or 2006. Professionally, was cropping layouts with Photoshop and exporting them as HTML (pretty modern, huh?).

At that time, I used to be an active member of several forums. Have heard of open source a lot, but had no idea what was the big deal with it. Everyone around me was talking about how .NET technologies were good because they had a solid company behind it.

Then I joined a game forum. Not an ordinary one, though. The specific matter was an emulator of an online game, and people there were always talking about this SVN that I had no idea what it was about. "Easy to contribute", "open source", they said. But to me, it was only a page with some anchors leading to folders to more and more files ending in `.c` or `.h` and I was "these guys are crazy.".

My English didn't help either. I'm Brazilian, as a matter of fact, and the subject in my country was very subtle you barely could see it. I was forced by headaches to stop trying to figure what this SVN and the "open source" were. Sincerely, I had an idea about what they could be but it was just an idea and nothing else.

Sharing files? Either 1) FTP, or 2) MegaUpload. In case I was physically with others, then was just standing behind their back. Regardless of the situation, never had the stomach to review code or to sit and understand how others used to write real code because exchanging knowledge through actual lines of code used to be a pain. The only code I used to spend some time reading and understanding were the ones from tutorials or books, but I rarely used to read the latter, so my code was a lone wolf.

The clock ticked and time has passed. 2009 was the year. I finally met GitHub "in person" and my life changed completely.

With a beautiful, intuitive, easy to understand even knowing nothing of the English language interface, the click of what was SVN and Open Source just happened. **I was amazed.**

Lots of developers out and about, people trying to help, issues on third-party libraries weren't a pain anymore, brand new frameworks and solutions for day-to-day problems all over the place... that was impressive for a kid like me.

"They have done the impossible," the kid thought, "they turned an inefficient, inorganic and robotic interface into this human thing!".

The kid grew up. Not that much because I'm still 22, but I have to say I'm only here today, writing this, because I was inspired by lots of fellow developers to code and to do it with passion. And remember when I mentioned that my relationship with GitHub went beyond code? I had to push myself to learn English either, and here we are.

Thank you, GitHub.

Wholeheartedly,
@chiefGui.

**Comment by fxn** [comment]
Hi, @chiefGui.

This is such a beautiful letter. This project has a lot of activity and I like to keep issues and PRs at zero, but I believe this post deserves an exception. I'll leave it open for some days, and then eventually we'll close.

Thanks for sharing! :heart:

**Comment by dynamicdebian** [comment]
Hi, @chiefGui.This is such a beautiful letter. This project has a lot of activity and I like to keep issues and PRs at zero, but I believe this post deserves an exception.Thanks for sharing!
--

**Comment by fxn** [comment]
Going to close finally, thanks again for sharing!
