### ISSUE TITLE
Remove emoticons from signatures

### ISSUE THREAD

**Issue by lnquy** [thank-you-github/thank-you-github#1101]
Hi all,
I don't want to offend anyone but some signatures has unnecessary emoticons and it's kind of annoying.
Since this repository is the place showing our gratitude to Github, not the place to gain attractions. I suggest we should remove all emoticons from signatures and won't accept any PR contains anything rather than basic information about signer.
I made a PR for this: https://github.com/thank-you-github/thank-you-github/pull/1099
Kind regards.

**Comment by fxn** [comment]
I already replied to you in the other issue. This is also not the place for you to impose your views about how the signature of others should be. Choose your style for yours, and let other choose their voice color too. They are just a nuance, and exceptional, definitely do not feel out of place to me.
