### ISSUE TITLE
Meh

### ISSUE THREAD

**Issue by vemv** [thank-you-github/thank-you-github#112]
GH sure did a bunch of awesome things, why should that imply that there's no room for improvement?

I find this repo a childish (however nicely worded) reaction, unempathetic with the real pain other OSS maintainers suffer.

We cannot accept that if you create a successful open source project, you will be DDoSed with issues, seriously affecting your project's health. Another Github is possible.

**Comment by thank-you-github** [comment]
I've read your remarks, thanks for your thoughts.
