### ISSUE TITLE
Please add hatry4 in the list

### ISSUE THREAD

**Issue by CharlesNaig** [thank-you-github/thank-you-github#2730]
Thanks for your signature. Make sure the following rules are correctly followed.

Please add your signature at the end of the list, at the bottom.

Just one line, following the pattern you can see in the existing ones.

Make sure the linked username in the signature matches exactly the GitHub handler of the account that opens the PR. This is the way to ensure the signature belongs to who has written the patch.

**Comment by brookmg** [comment]
Create a pull request not an issue.
