### ISSUE TITLE
Incorrect newline after merge

### ISSUE THREAD

**Issue by xor-gate** [thank-you-github/thank-you-github#416]
It seems after merging the last three PR there is a spurious newline which results in a broken list:

![2016-03-07 11_47_48-thank-you-github_thank-you-github_ an open letter of gratitude to github](https://cloud.githubusercontent.com/assets/1050166/13567262/8e6e7440-e45a-11e5-802b-ae0fd9600f7b.png)

**Comment by fxn** [comment]
Fixed in 4e29dcd0a0296ecf04f90a520dd0b4959203afbd, thanks for opening the issue :heart:.
