### ISSUE TITLE
I agree!

### ISSUE THREAD

**Issue by gustavoschmidt** [thank-you-github/thank-you-github#79]
+1

**Comment by thank-you-github** [comment]
Would you like to sign? Just open a PR for the README and add yourself!

**Comment by cfmacedo** [comment]
+1

**Comment by thank-you-github** [comment]
Keeping 0 counts in the tab bar... please sign if you'd like to!

**Comment by devesh** [comment]
Amusingly, the +1s polluting the comments for this issue represent one of the problems raised by the Dear Github letter that this Thank You letter is passive-aggressively pooh-poohing.

**Comment by thank-you-github** [comment]
Except they are not perceived as a problem by this project's maintainer.

**Comment by gustavoschmidt** [comment]
@devesh 
haha, you got my joke ;)

@thank-you-github 
I agree with every word you've written in the Readme, Github is indeed awesome, but of course it can be improved. o/

**Comment by thank-you-github** [comment]
@gustavoschmidt absolutely, this post does not even imply it cannot be improved.

**Comment by asdofindia** [comment]
+1
