### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by jsroyal** [thank-you-github/thank-you-github#885]
It would be great to add PULL_REQUEST_TEMPLATE.
So it will easy to merge.
Maybe in alphabet order will be good on the list.

**Comment by lockys** [comment]
I don't think alphabet order is needed.
First come, first service is ok

**Comment by jsroyal** [comment]
@lockys I agree your thought FCFS 
But just think about if you want to search for someone profile then how it will easy to get it if it Alphabet order.Just for e.g. when my PR merged and I just wanted to check where is my entry, it was very tough to search coz it is going very rapidly merging which take a lot of scrolls up and down. 

Let's check majority opinion.
it was just my single thought.

**Comment by fxn** [comment]
Sorting is fine, see https://github.com/thank-you-github/thank-you-github/issues/998#issuecomment-338606926. But there are some minimal requirements for valid signatures that could be explained in a PR template, since I do not want to put administrative stuff in the README. 

I'll work on that, thanks.

**Comment by fxn** [comment]
In the end I have added [contributing guidelines](https://github.com/thank-you-github/thank-you-github/blob/master/CONTRIBUTING.md), which seems more adequate for the purpose explained above.

Thanks for the feedback!

**Comment by fxn** [comment]
For the archives: In addition to the [contributing guidelines](https://github.com/thank-you-github/thank-you-github/blob/master/.github/CONTRIBUTING.md) there is now additionally a [PR template](https://github.com/thank-you-github/thank-you-github/blob/master/.github/PULL_REQUEST_TEMPLATE.md) that tells you the PR is likely going to be closed via a commit.

I think we cover everything with those two documents. Thanks again for the feedback!
