### ISSUE TITLE
Why do you decline signatures without a reason ?

### ISSUE THREAD

**Issue by StarpTech** [thank-you-github/thank-you-github#913]
As titled.

**Comment by drm2** [comment]
+1

**Comment by drm2** [comment]
Looks like he's just pulling in the changes himself instead of merging the PR.

https://github.com/thank-you-github/thank-you-github/blame/master/README.md#L804

**Comment by StarpTech** [comment]
Correct, but it's confusing.

**Comment by fxn** [comment]
All signatures that seem legit get in, everyone can sign.

This letter got a some attention when it was written in 2015. After that there has been a steady stream of signatures, and another peak lately.

Think everybody is editing the same file, so practically no PR is mergeable. Asking people to rebase would be very slow and impractical given the number of PRs. I wrote back in the day a script that fetches the patches, does some sanity check on them, and presents them to me one by one for confirmation. Supervised merges.

**Comment by G07cha** [comment]
By the way, there is a possibility to define a "union" as a default strategy for merging in [.gitattributes](https://git-scm.com/docs/gitattributes#gitattributes-union), which will automatically keep all conflicting changes in place, although it will definitely require manual validation before merging.

**Comment by StarpTech** [comment]
For future projects like this it would be useful to go with this approach:

- Any signature is a separate file.
- Create a simple script to create the summary.

**Comment by fxn** [comment]
Thanks for your ideas.

I believe the current flow is fine though. People can very easily add a new signature, and I can validate and commit a dozen valid signatures in no time. The author of the PR has of course a notification that says that the PR was closed by a specific commit where they can see their signature added, and their name in the commit message:

<img width="583" alt="screen shot 2017-10-22 at 23 10 16" src="https://user-images.githubusercontent.com/3387/31866334-909ca4f0-b77e-11e7-8081-ea2eb890a7dd.png">

There has be about 60 new signatures added only today.

There is also an etiquette rule that says that each signature has to be added to the bottom... I think it is all OK.
